variables:
  BUILD_IMAGES_PROJECT: openconnect/build-images
  CENTOS6_BUILD: openconnect-cli-centos6
  CENTOS7_BUILD: openconnect-cli-centos7
  CENTOS8_BUILD: openconnect-cli-centos8
  FEDORA_BUILD: openconnect-cli-fedora
  UBUNTU_BUILD: openconnect-cli-ubuntu

image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD

CentOS7/GnuTLS:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$CENTOS7_BUILD
  script:
  - ./autogen.sh
  - ./configure --with-java --enable-ppp-tests CFLAGS=-g
  - make -j4
# UTF-8 support is not available
  - make VERBOSE=1 XFAIL_TESTS="auth-nonascii" -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

CentOS7/OpenSSL:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$CENTOS7_BUILD
  script:
  - ./autogen.sh
  - ./configure --without-gnutls --with-openssl --with-java --without-openssl-version-check --enable-dtls-xfail --disable-dsa-tests --enable-ppp-tests CFLAGS=-g
  - make -j4
# auth-nonascii: UTF-8 support is not available
# dtls-psk: communication with ocserv fails for undetermined reasons marking as xfail until issue is identified
  - make VERBOSE=1 XFAIL_TESTS="auth-nonascii dtls-psk" -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log
