variables:
  BUILD_IMAGES_PROJECT: openconnect/build-images
  CENTOS6_BUILD: openconnect-cli-centos6
  CENTOS7_BUILD: openconnect-cli-centos7
  CENTOS8_BUILD: openconnect-cli-centos8
  FEDORA_BUILD: openconnect-cli-fedora
  UBUNTU_BUILD: openconnect-cli-ubuntu

image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD

Ubuntu18.04/GnuTLS:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$UBUNTU_BUILD
  script:
  - ./autogen.sh
  - ./configure --with-java CFLAGS=-g --enable-ppp-tests
  - make -j4
# UTF-8 support is not available
  - make VERBOSE=1 XFAIL_TESTS="auth-nonascii" -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log
